[package]
name = "broken-deploy-example"
version = "0.1.0"
edition = "2021"
publish = false

[lib]

[dependencies]
shuttle-service = { version = "0.7.2", features = ["web-thruster"] }
thruster = { version = "1.3.0", features = ["hyper_server"] }
web-push = "0.9.2"
